name: 'CI'
on: [push, pull_request]
jobs:
  test:
    name: Test (go ${{matrix.go}})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        go: ['1.18', '1.19', '1.20', '1.21']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - run: make test

  test-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-kubectl@v4.0.0
    - uses: azure/setup-helm@v4.2.0
      with:
        version: v3.11.1
    - uses: engineerd/setup-kind@v0.6.2
      with:
        version: "v0.17.0" # Version of Kind to use
    - run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo add stable https://charts.helm.sh/stable
        helm repo update
    - uses: ./.
      with:
        release-name: 'test-release'
        chart: 'bitnami/nginx'
        namespace: test-namespace
        create-namespace: true
        debug: true
        wait: true
        timeout: 10m
        sets: >
          service.type=ClusterIP
          myValue=test
    - if: failure()
      run: |
        kubectl config set-context kind-kind --namespace test-namespace
        kubectl get pods
        echo "==========================="
        kubectl get pods --no-headers | awk '{print $1}' | xargs -L 1 kubectl logs
