name: 'CI'
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.2
    - run: make test

  test-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: azure/setup-kubectl@v3.2
    - uses: azure/setup-helm@v3.5
      with:
        version: v3.11.1
    - uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.17.0" # Version of Kind to use
    - run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo add stable https://charts.helm.sh/stable
        helm repo update
    - uses: ./.
      with:
        release-name: 'test-release'
        chart: 'bitnami/nginx'
        namespace: test-namespace
        create-namespace: true
        debug: true
        wait: true
        timeout: 10m
        sets: >
          service.type=ClusterIP
          myValue=test
    - if: failure()
      run: |
        kubectl config set-context kind-kind --namespace test-namespace
        kubectl get pods
        echo "==========================="
        kubectl get pods --no-headers | awk '{print $1}' | xargs -L 1 kubectl logs
